"""English copy for the shared, screenshot-based YouTube renderer."""

COPY = {
    'Pourquoi blink2video ?': 'Why blink2video?',
    'Blink est pensé pour le téléphone. Mais comment garder un historique sur ordinateur ?': 'Blink is built for your phone. How do you keep a video history on your computer?',
    'Ne perdez pas le fil.': 'Keep the whole story.',
    'Récupérez les clips avant leur effacement et rassemblez-les dans une archive.': 'Download clips before they expire and bring them together in an archive.',
    'Vos caméras Blink.\nSur votre ordinateur.': 'Your Blink cameras.\nOn your computer.',
    'Le direct et vos archives, avec blink2video.': 'Live view and video archives, with blink2video.',
    'Retrouvez vos clips.': 'Find your recordings.',
    'Les enregistrements réunis dans une interface locale.': 'Your recordings together in one local interface.',
    'Le bon moment.\nLa bonne caméra.': 'The right moment.\nThe right camera.',
    'Filtrez par caméra et par période.': 'Filter by camera and time period.',
    'Gardez aussi le direct.': 'Record live view, too.',
    'Lancez un direct et enregistrez-le à la demande.': 'Open a live stream and record it whenever you need to.',
    'Récupérez les nouveaux clips.': 'Download new clips.',
    'Stockage du module et cloud : deux sources prises en charge.': 'Module storage and the cloud: both sources are supported.',
    'Des clips à une archive.': 'Turn clips into an archive.',
    'Une vidéo par caméra, par jour, par semaine et par mois.': 'One video per camera, per day, per week and per month.',
    'Vos vidéos, sur votre machine.': 'Your videos, on your computer.',
    'Date et heure incrustées. Clips sans intérêt mis de côté.': 'Date and time in the picture. Unwanted clips set aside.',
    '1. Télécharger et installer.': '1. Download and install.',
    'Sur GitHub, ouvrez la dernière version publiée et choisissez votre système.': 'Open the latest release on GitHub and choose your operating system.',
    '2. Lancer et se connecter.': '2. Launch and sign in.',
    'Ouvrez blink2video, puis connectez-vous à votre compte Blink dans le navigateur.': 'Open blink2video, then sign in to your Blink account in the browser.',
    '3. Valider le premier démarrage.': '3. Complete the first setup.',
    'Choisissez le dossier des vidéos et le fuseau horaire, puis cliquez sur Appliquer.': 'Choose your video folder and time zone, then click Apply.',
    'Réglages : au quotidien.': 'Settings: everyday use.',
    'Démarrage automatique, actualisation de la page, téléchargement et cadence de lecture.': 'Automatic startup, page refresh, downloads and polling intervals.',
    'Réglages : vos vidéos.': 'Settings: your videos.',
    'Horodatage, fuseau horaire, protocole du direct et archives par jour, semaine ou mois.': 'Timestamps, time zone, live view playback and daily, weekly or monthly archives.',
    'Réglages : garder la main.': 'Settings: stay in control.',
    'Alertes par caméra, suppression à la source après téléchargement et arrêt de la surveillance.': 'Per-camera alerts, optional deletion after download, and stopping monitoring.',
    'À vous de jouer.': 'Try it yourself.',
    'Le point de départ': 'The starting point',
    'Vous regardez vos caméras Blink sur votre téléphone.': 'You watch your Blink cameras on your phone.',
    'Le besoin': 'The missing piece',
    'Voir le direct et retrouver vos enregistrements sur ordinateur.': 'Watch live view and find your recordings on your computer.',
    'L’idée de blink2video': 'The idea behind blink2video',
    'Réunir vos caméras, vos clips et vos archives au même endroit.': 'Bring your cameras, clips and video archives together in one place.',
    'Des clips dispersés': 'Separate clips',
    'Un événement peut être réparti sur plusieurs enregistrements.': 'A single event can span several recordings.',
    'Une conservation limitée': 'Limited retention',
    'Le stockage local se remplit ; le cloud garde les clips un temps limité.': 'Local storage fills up; the cloud keeps clips for a limited time.',
    'Un historique chez vous': 'A history you can keep',
    'Télécharger les clips et les assembler pour les revoir facilement.': 'Download and combine clips so you can easily watch them again.',
    'Ouvrir le lien dans la description': 'Open the link in the description',
    'Choisir l’archive de votre système': 'Choose the archive for your system',
    'Windows : .zip  ·  Linux : .tar.gz  ·  macOS Apple Silicon : .zip': 'Windows: .zip  ·  Linux: .tar.gz  ·  macOS Apple Silicon: .zip',
    'Décompresser dans un dossier': 'Extract the archive into a folder',
    'Conservez tous les fichiers ensemble. Guide détaillé sur GitHub.': 'Keep all files together. The full setup guide is on GitHub.',
    'Double-cliquez sur blink2video.exe dans le dossier décompressé.': 'Double-click blink2video.exe in the extracted folder.',
    'Linux et macOS': 'Linux and macOS',
    'Dans un terminal : ./blink2video — préparation expliquée sur GitHub.': 'In a terminal: ./blink2video — see GitHub for first-run preparation.',
    'Connexion dans le navigateur': 'Sign in through your browser',
    'Adresse e-mail, mot de passe Blink, puis code de vérification Blink.': 'Enter your email, Blink password, then the Blink verification code.',
    'Au tout premier lancement': 'On your very first launch',
    'Le panneau Réglages s’ouvre automatiquement après la connexion.': 'The Settings panel opens automatically after you sign in.',
    'Dossier des données et fuseau horaire': 'Data folder and time zone',
    'Choisissez où conserver les vidéos et quelle heure afficher.': 'Choose where to store your videos and which time zone to display.',
    'Cliquer sur « Appliquer »': 'Click Apply',
    'Le téléchargement et l’assemblage peuvent alors démarrer.': 'Clip downloading and video assembly can now begin.',
    'Démarrage et affichage': 'Startup and display',
    'Lancer à l’ouverture de session et actualiser automatiquement la page.': 'Start when you log in and refresh the page automatically.',
    'Téléchargement automatique': 'Automatic downloads',
    'Activer la récupération ; choisir une cadence locale et une cadence cloud.': 'Enable downloads; set separate intervals for local storage and cloud.',
    'Accès et stockage': 'Access and storage',
    'Modifier le dossier des données ou, si nécessaire, le port du serveur.': 'Change the data folder or, if needed, the server port.',
    'Date et heure dans l’image': 'Date and time in the picture',
    'Activer l’horodatage et choisir votre fuseau horaire.': 'Enable timestamps and choose your time zone.',
    'Direct : WebRTC ou MSE': 'Live view: WebRTC or MSE',
    'Choisir le protocole de lecture du direct dans le navigateur.': 'Choose how live view plays in your browser.',
    'Vidéos assemblées': 'Combined videos',
    'Activer séparément les archives quotidiennes, hebdomadaires et mensuelles.': 'Enable daily, weekly and monthly archives independently.',
    'Alertes par caméra': 'Per-camera alerts',
    'Mettre en sourdine les alertes des caméras de votre choix.': 'Mute alerts for the cameras you choose.',
    'Suppression automatique après téléchargement': 'Delete automatically after download',
    'Option par caméra : supprime les clips à la source après récupération.': 'Per-camera option: delete clips at the source after downloading them.',
    'Appliquer ou arrêter': 'Apply or stop',
    'Valider les changements ; le bouton rouge arrête la surveillance.': 'Apply your changes; the red button stops monitoring.',
    'VOS CAMÉRAS. VOS ARCHIVES.': 'YOUR CAMERAS. YOUR ARCHIVES.',
    'L’ordinateur doit rester allumé pour récupérer et assembler les clips.': 'Your computer must stay on to download and combine clips.',
    'Aucune installation de Python nécessaire avec les archives publiées.': 'The release bundles do not require a separate Python installation.',
    'Un jeton de session est conservé ; jamais votre mot de passe.': 'Only a session token is stored, never your password.',
    'Aucun clip n’est téléchargé avant cette première validation.': 'No clips are downloaded until you confirm this first setup.',
    'Pour rouvrir les réglages : cliquez sur l’engrenage en haut à droite.': 'To reopen Settings, click the gear icon in the top-right corner.',
    'Les trois périodicités d’archives sont indépendantes.': 'The three archive schedules can be enabled independently.',
    'La suppression à la source est facultative : choisissez-la en connaissance de cause.': 'Deleting clips at the source is optional. Enable it only if you want them removed.',
    'LE DIRECT ET VOS ARCHIVES': 'LIVE VIEW AND VIDEO ARCHIVES',
    'DIRECT': 'LIVE VIEW',
    'Aujourd’hui · Semaine · Mois': 'Today · Week · Month',
    '1. Ouvrir le direct': '1. Open live view',
    '2. Enregistrer': '2. Start recording',
    'À conserver dans\nvos enregistrements.': 'Saved with your\nlive recordings.',
    'STOCKAGE LOCAL': 'LOCAL STORAGE',
    'CLOUD BLINK': 'BLINK CLOUD',
    'Clips de votre abonnement\nBlink': 'Clips from your Blink\nsubscription',
    'Seuls les nouveaux clips sont téléchargés.': 'Only new clips are downloaded.',
    '01 JOUR': '01 DAY',
    'Une journée réunie': 'A whole day together',
    '01 SEMAINE': '01 WEEK',
    'Une vue plus large': 'A wider view',
    '01 MOIS': '01 MONTH',
    'Votre historique': 'Your video history',
    'Assemblage automatique, caméra par caméra.': 'Combined automatically, camera by camera.',
    'Horodater': 'Add timestamps',
    'La date et l’heure restent visibles dans l’image.': 'The date and time stay visible in the picture.',
    'Faire le tri': 'Sort your clips',
    'Écartez un clip sans supprimer son original.': 'Discard a clip without deleting the original.',
    'Conserver': 'Keep your videos',
    'Retrouvez vos fichiers vidéo sur votre ordinateur.': 'Find your video files on your computer.',
    'Gratuit et open source': 'Free and open source',
    'Téléchargement et installation : lien dans la description.': 'Download and setup instructions: link in the description.',
    'Un projet indépendant, sans affiliation avec Blink ou Amazon.': 'An independent project, not affiliated with Blink or Amazon.',
    'BLINK\nSUR VOTRE PC': 'BLINK\nON YOUR PC',
    'DIRECT + ARCHIVES': 'LIVE VIEW + ARCHIVES',
    'Sync Module 2 : USB\nSync Module XR : microSD': 'Sync Module 2: USB\nSync Module XR: microSD',
}

SCREENSHOTS = {
    'serve0.fr.PNG': 'serve0.PNG',
    'filtre.fr.PNG': 'filtre.PNG',
    'direct_record_fr.PNG': 'direct_record_en.PNG',
}
